AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  fetch-nextbus

  Get data from NextBus and relay via SNS

Globals:
  Function:
    Timeout: 60

Resources:
  FetchNextBusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/fetch-nexbus-1.0-SNAPSHOT.jar
      Handler: jck.LambdaRequest::handleRequest
      Runtime: java8
      MemorySize: 192
      Policies: 
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: '*'
      Environment:
        Variables:
          SNS_Topic_ARN: !Ref NextBusUpdateSnsTopic

  NextBusUpdateSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NextBus Position Updates
      # KmsMasterKeyId: String
      # Subscription:
      #   - SNS Subscription
      # TopicName: bus_update

  NextBusUpdateSnsTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref NextBusUpdateSnsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sns:Publish'
            Resource: !Ref NextBusUpdateSnsTopic
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt FetchNextBusFunction.Arn
            Principal:
              AWS: '*'


Outputs:
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  FetchNextBusFunction:
    Description: "FetchNextBus ARN"
    Value: !GetAtt FetchNextBusFunction.Arn

  FetchNextBusFunctionIamRole:
    Description: "Implicit IAM Role created for FetchNextBus function"
    Value: !GetAtt FetchNextBusFunctionRole.Arn
